### ISSUE TITLE
REM To-Do list for publishing on GF

### ISSUE THREAD

**Issue by vv-monsalve** [octaviopardo/REM#8]
- [x] Solve the [open corners issue](https://github.com/octaviopardo/REM/issues/7)
- [ ] Review/edit the information files (Description, Authors, Contributors)
- [ ] Review the [Outline Quality Checklist](https://github.com/octaviopardo/REM/issues/5) and ensure everything is ok in REM
